POST http://localhost:3001/api/trigger/transaction
Content-Type: application/json

{
  "webhook": "http://localhost:3001/api/trigger",
  "sender_id": "EQMBBVYGZOFUIHEXFOXKTFTANEKBXLBXHAYDFFMREEMRQEVADYMMEWACTODD",
  "min_qubic": 1000000
}

###
